env:
  es2021: true
  node: true
  'jest/globals': true
extends:
  - eslint:recommended
  - plugin:eslint-comments/recommended
  - plugin:jest/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'jest'
  - 'prettier'
ignorePatterns:
  - 'dist'
rules:
  {
    'arrow-body-style': 'off',
    'prefer-arrow-callback': 'off',
    'no-empty-pattern': 0,
    'no-unused-vars': 'off',
    'no-mixed-operators': 'error',
    '@typescript-eslint/no-unused-vars': 'error',
    'quotes': [2, 'single', { 'avoidEscape': true }],
    'no-shadow': 'off',
    '@typescript-eslint/no-shadow': ['error'],
    'prettier/prettier': 'error',
  }
